name: 🚅 Feature branch Build [ubuntu-latest]
on:
  workflow_run:
    workflows: ['Assert Branch Naming Convention']
    types:
      - completed

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Set the build number in MinVer.
  MINVERBUILDMETADATA: build.${{github.run_number}}

jobs:
  build:
    name: Build-${{matrix.os}}  by @${{ github.actor }}

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout  by @${{ github.actor }}
        uses: actions/checkout@v3.0.2
        with:
          lfs: true
          fetch-depth: 0
      - name: Install .NET SDK  by @${{ github.actor }}
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: |
            8.0.x
      - name:  Dotnet  Restore by @${{ github.actor }}
        run: dotnet restore
        shell: pwsh
      - name: 🔨 Dotnet  Build  by @${{ github.actor }}
        run: dotnet build --no-restore --configuration Release
        shell: pwsh
      
